name: fluxon_method_generator
description: Code generator for fluxon service contracts (clients/dispatchers)
version: 0.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

homepage: https://github.com/KevinVan720/flux
repository: https://github.com/KevinVan720/flux

dependencies:
  analyzer: ^7.2.0
  build: ^3.0.0
  source_gen: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.0

